### ISSUE TITLE
Unicode issue python 3.6 

### ISSUE THREAD

**Issue by neilh** [bradleyg/django-s3direct#148]
> pip install django-s3direct

Collecting django-s3direct
  Using cached django-s3direct-1.0.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-7msb0us6/django-s3direct/setup.py", line 5, in <module>
        readme = f.read()
      File "env/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 6326: ordinal not in range(128)

**Comment by bradleyg** [comment]
I think this is fixed in the latest release.

Thanks
