### ISSUE TITLE
File input doesn't show up

### ISSUE THREAD

**Issue by WollenMoth** [bradleyg/django-s3direct#244]
I'm trying to use django-s3direct on the admin page.
Followed the steps to use the example, but inputs doesn't appear in admin form.

![image](https://user-images.githubusercontent.com/27463216/154186526-704306c5-d9d5-46cc-b2b6-45bc854c61a8.png)

I'm using Python 3.10 and Django 4.0.2

I would like to use django-s3direct in other proyect with the same versions, so I cannot downgrade.

**Comment by WollenMoth** [comment]
Form page doesn't work either.

![image](https://user-images.githubusercontent.com/27463216/154186799-76f2ee82-f5bf-415d-ac09-8106ddeec63a.png)

And I'm getting this error on the browser console.

`index.js:1 Uncaught TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
    at index.js:1:90982
    at index.js:1:91031`

**Comment by klausqian** [comment]
I encountered the same error using the latest (2.0.0) release, downgraded to 1.1.8 worked. 

python 3.10, djanog 3.25, djang-s3direct 1.1.8

**Comment by byteofwood** [comment]
I think I discovered what is causing this issue. s3direct's script tag is inserted in the head. This means that this part of s3direct's script (the last ~150 chars of `/static/s3direct/dist/index.js`, prettified) is run before the page is fully loaded.
```
...
new MutationObserver((function(t) {
    [].forEach.call(document.querySelectorAll('.s3direct'), A)
}))
    .observe(document.body, {
        childList: !0,
        subtree: !0
    })
```
I believe document.body is null at the time it is run which causes the "parameter 1 is not of type 'Node'." I bodged this by putting the script at the end of the body by adding to the admin template. Info in [this SO answer](https://stackoverflow.com/a/57788833).

My /templates/admin/base_site.html file:
```
{% extends 'admin/base_site.html' %}
{% load static %}

{% block footer %}
    <div id="footer"></div>
    <script src="/static/s3direct/dist/index.js"></script>
{% endblock %}
```

This fixes the input not showing up problem for me. Hopefully there is a better way to solve this, perhaps [jquery's .ready()](https://api.jquery.com/ready/), [javascript's window.onload](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onload), or by somehow telling django to put the script at the end of the body (I'm not sure if this is possible using the Media class), or maybe even putting the script in the [widget's template](https://github.com/bradleyg/django-s3direct/blob/master/s3direct/templates/s3direct/s3direct-widget.tpl).

**Comment by bradleyg** [comment]
Should be fixed in the latest release.
